openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /api/item_list:
    get:
      summary: Get rec item list
      description: Retrieve list about a user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        itemId:
          type: string
        score:
          type: double
